# Generated by Django 4.2.7 on 2023-11-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='ISO', max_length=255),
        ),
    ]
